# Generated by Django 6.0 on 2025-12-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_channel_id', models.BigIntegerField(help_text='Discord channel ID where reports will be sent', unique=True)),
                ('enabled', models.BooleanField(default=True, help_text='Whether the report system is enabled')),
            ],
            options={
                'verbose_name': 'Report Configuration',
                'verbose_name_plural': 'Report Configurations',
                'db_table': 'report_config',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(help_text='Discord user ID of the reporter')),
                ('user_name', models.CharField(help_text='Discord username of the reporter', max_length=255)),
                ('report_type', models.CharField(choices=[('violation', 'Report Violation'), ('bug', 'Report Bug'), ('suggestion', 'Provide Suggestion'), ('other', 'Other')], help_text='Type of report', max_length=20)),
                ('content', models.TextField(help_text='Report content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the report was created')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='Metadata about attachments (filename, url, etc.)')),
                ('replied', models.BooleanField(default=False, help_text='Whether admin replied')),
                ('reply_time', models.DateTimeField(blank=True, help_text='When the reply was sent', null=True)),
                ('reply_by', models.CharField(blank=True, help_text='Username of the admin who replied', max_length=255, null=True)),
                ('reply_content', models.TextField(blank=True, help_text="Content of the admin's reply", null=True)),
                ('discord_message_id', models.BigIntegerField(blank=True, help_text='ID of the report message in Discord', null=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'report',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['user_id'], name='report_user_id_b99432_idx'), models.Index(fields=['report_type'], name='report_report__a84470_idx'), models.Index(fields=['replied'], name='report_replied_301e9c_idx'), models.Index(fields=['created_at'], name='report_created_2a12c2_idx')],
            },
        ),
    ]
